const CHANGE_DESCRIPTION = "CHANGE_DESCRIPTION"
const CLEAN_FORM = "CLEAN_FORM"
const TODO_SEARCH = "TODO_SEARCH"
const TODO_ADD = "TODO_ADD"
const TODO_MARK_DONE = "TODO_MARK_DONE"
const TODO_MARK_PENDING = "TODO_MARK_PENDING"
const TODO_DELETE = "TODO_DELETE"
export {CHANGE_DESCRIPTION,TODO_SEARCH,TODO_ADD,TODO_MARK_DONE,TODO_MARK_PENDING,TODO_DELETE,CLEAN_FORM}